In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [8]:
X_train

array([[-0.79192278, -0.23326772, -0.73339155, ...,  0.10142953,
         0.66921009,  2.52063691],
       [-0.80319456,  0.1559987 , -0.84091621, ..., -1.3628983 ,
        -0.56889162, -0.45853596],
       [ 0.83685013,  1.89345611,  0.79035136, ...,  0.62932691,
         0.17792605,  0.34617995],
       ...,
       [-0.51012816, -0.77681655, -0.53306045, ..., -1.05226907,
        -0.69253693, -1.18539408],
       [-0.74683564, -0.24038844, -0.74729208, ..., -0.94355667,
        -1.14425447, -0.44463278],
       [-0.33823344, -0.6747528 , -0.38179002, ..., -0.51653937,
         0.20100651, -0.82780435]])

In [9]:
y_train

242    B
522    B
460    M
226    B
476    B
      ..
60     B
161    M
189    B
304    B
195    B
Name: diagnosis, Length: 455, dtype: object

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [11]:
y_train

array([0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

## NumPy arrays to PyTorch tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor

tensor([[-0.7919, -0.2333, -0.7334,  ...,  0.1014,  0.6692,  2.5206],
        [-0.8032,  0.1560, -0.8409,  ..., -1.3629, -0.5689, -0.4585],
        [ 0.8369,  1.8935,  0.7904,  ...,  0.6293,  0.1779,  0.3462],
        ...,
        [-0.5101, -0.7768, -0.5331,  ..., -1.0523, -0.6925, -1.1854],
        [-0.7468, -0.2404, -0.7473,  ..., -0.9436, -1.1443, -0.4446],
        [-0.3382, -0.6748, -0.3818,  ..., -0.5165,  0.2010, -0.8278]],
       dtype=torch.float64)

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

## Defining the model

In [22]:
class MySimpleNeuralNetwork():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    loss = -(y_train_tensor*torch.log(y_pred) + (1-y_train_tensor)*torch.log(1-y_pred))
    return loss.mean()

## Important parameters

In [23]:
learning_rate = 0.1
epochs = 25

## Training pipeline

In [25]:
# create model
model = MySimpleNeuralNetwork(X_train_tensor)

for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculation
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f"Epoch {epoch}: Loss = {loss.item()}")

Epoch 0: Loss = 3.5821064938841998
Epoch 1: Loss = 3.466364084073085
Epoch 2: Loss = 3.346723450293138
Epoch 3: Loss = 3.22638070543463
Epoch 4: Loss = 3.101414171560196
Epoch 5: Loss = 2.974928690851594
Epoch 6: Loss = 2.838732328992532
Epoch 7: Loss = 2.697859757706644
Epoch 8: Loss = 2.5559155862016287
Epoch 9: Loss = 2.4130825861114995
Epoch 10: Loss = 2.2654644441277543
Epoch 11: Loss = 2.120809169957221
Epoch 12: Loss = 1.9797167383242933
Epoch 13: Loss = 1.8440916239462877
Epoch 14: Loss = 1.7137030451336328
Epoch 15: Loss = 1.592400376949493
Epoch 16: Loss = 1.479458907377103
Epoch 17: Loss = 1.369742303653496
Epoch 18: Loss = 1.269713012321544
Epoch 19: Loss = 1.1818068405940154
Epoch 20: Loss = 1.1083020344335677
Epoch 21: Loss = 1.0486672973299365
Epoch 22: Loss = 1.001448803971372
Epoch 23: Loss = 0.964515872682139
Epoch 24: Loss = 0.9355781904876906


In [27]:
model.weights

tensor([[ 0.2310],
        [-0.1956],
        [ 0.2416],
        [-0.2694],
        [ 0.4194],
        [-0.2446],
        [-0.4807],
        [-0.4055],
        [-0.1754],
        [ 0.3600],
        [ 0.4002],
        [ 0.6047],
        [ 0.2428],
        [ 0.3941],
        [-0.1150],
        [-0.3508],
        [ 0.3220],
        [-0.1885],
        [ 0.7019],
        [ 0.0270],
        [ 0.3084],
        [ 0.2921],
        [-0.1201],
        [ 0.2335],
        [ 0.2436],
        [-0.2655],
        [ 0.1709],
        [-0.3334],
        [ 0.4315],
        [ 0.2666]], dtype=torch.float64, requires_grad=True)

In [28]:
model.bias

tensor([-0.1281], dtype=torch.float64, requires_grad=True)

## Evaluation

In [35]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5160049200057983
