In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [8]:
X_train

array([[-0.73777812, -0.15253276, -0.76397125, ..., -0.7706937 ,
         0.7018915 , -0.77082557],
       [-0.37690037, -0.44172814, -0.36666645, ..., -0.47115213,
        -1.45462397, -0.76110389],
       [ 1.11172034,  0.54019105,  1.03883507, ..., -0.33726612,
        -0.83123065, -1.04417635],
       ...,
       [ 0.84670075, -0.67936155,  0.98155116, ...,  2.13153131,
         1.94540574,  1.2615775 ],
       [-0.07522913,  0.28462304, -0.09170371, ..., -0.69066466,
        -1.027575  ,  0.06180777],
       [-0.32051323,  0.30255764, -0.3478446 , ..., -0.77371937,
         0.52190918, -1.11451556]])

In [9]:
y_train

55     B
397    B
197    M
509    M
393    M
      ..
73     M
135    M
25     M
544    B
150    B
Name: diagnosis, Length: 455, dtype: object

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [11]:
y_train

array([0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,

## NumPy arrays to PyTorch tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor

tensor([[-0.7378, -0.1525, -0.7640,  ..., -0.7707,  0.7019, -0.7708],
        [-0.3769, -0.4417, -0.3667,  ..., -0.4712, -1.4546, -0.7611],
        [ 1.1117,  0.5402,  1.0388,  ..., -0.3373, -0.8312, -1.0442],
        ...,
        [ 0.8467, -0.6794,  0.9816,  ...,  2.1315,  1.9454,  1.2616],
        [-0.0752,  0.2846, -0.0917,  ..., -0.6907, -1.0276,  0.0618],
        [-0.3205,  0.3026, -0.3478,  ..., -0.7737,  0.5219, -1.1145]],
       dtype=torch.float64)

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

In [23]:
from torch.utils.data import Dataset, DataLoader

In [24]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):

    return self.features.shape[0]

  def __getitem__(self, index):

    return self.features[index], self.labels[index]

In [25]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [26]:
train_dataloader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_dataloader = DataLoader(test_dataset, batch_size=32, shuffle=True)

## Defining the model

In [27]:
class MySimpleNeuralNetwork(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

## Important parameters

In [28]:
learning_rate = 0.1
epochs = 25

In [29]:
loss_function = nn.BCELoss()

In [30]:
type(loss_function)

torch.nn.modules.loss.BCELoss

## Training pipeline

In [33]:
model = MySimpleNeuralNetwork(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(epochs):

  for batch_features, batch_labels in train_dataloader:

    # forward pass
    y_pred = model.forward(batch_features.float())

    # loss calculation
    loss = loss_function(y_pred, batch_labels.view(-1,1).float())

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

    # print loss in each epoch
    print(f"Epoch {epoch}: Loss = {loss.item()}")

Epoch 0: Loss = 0.5868123769760132
Epoch 0: Loss = 0.6466879844665527
Epoch 0: Loss = 0.39120906591415405
Epoch 0: Loss = 0.3287295699119568
Epoch 0: Loss = 0.37844565510749817
Epoch 0: Loss = 0.3370737135410309
Epoch 0: Loss = 0.3958500921726227
Epoch 0: Loss = 0.2564338147640228
Epoch 0: Loss = 0.3594047427177429
Epoch 0: Loss = 0.20695377886295319
Epoch 0: Loss = 0.26718324422836304
Epoch 0: Loss = 0.2739551067352295
Epoch 0: Loss = 0.1839459240436554
Epoch 0: Loss = 0.31735336780548096
Epoch 0: Loss = 0.29133695363998413
Epoch 1: Loss = 0.08446749299764633
Epoch 1: Loss = 0.22284157574176788
Epoch 1: Loss = 0.2718484401702881
Epoch 1: Loss = 0.2073460817337036
Epoch 1: Loss = 0.21691693365573883
Epoch 1: Loss = 0.13603509962558746
Epoch 1: Loss = 0.2758241295814514
Epoch 1: Loss = 0.2166210561990738
Epoch 1: Loss = 0.14696918427944183
Epoch 1: Loss = 0.1633060723543167
Epoch 1: Loss = 0.21667179465293884
Epoch 1: Loss = 0.1951185166835785
Epoch 1: Loss = 0.11021322757005692
Epoch 1

In [34]:
model.linear.weight

Parameter containing:
tensor([[ 0.3823,  0.4686,  0.4883,  0.4322,  0.2486,  0.0970,  0.3706,  0.5559,
         -0.0042, -0.3370,  0.7063, -0.0576,  0.3489,  0.6133,  0.1451, -0.3332,
         -0.1915,  0.1831, -0.2355, -0.2874,  0.5787,  0.7564,  0.5633,  0.7414,
          0.5269,  0.2813,  0.5198,  0.6094,  0.4217,  0.1749]],
       requires_grad=True)

In [35]:
model.linear.bias

Parameter containing:
tensor([-0.4742], requires_grad=True)

## Evaluation

In [36]:
model.eval()
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_dataloader:
    y_pred = model.forward(batch_features.float())
    y_pred = (y_pred > 0.5).float()
    batch_accuracy = (y_pred == batch_labels).float().mean()
    accuracy_list.append(batch_accuracy)

overall_accuracy = sum(accuracy_list)/len(accuracy_list)
print(f"Accuracy: {overall_accuracy}")

Accuracy: 0.5397678017616272
