In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [8]:
X_train

array([[ 1.46194246,  0.94111894,  1.48743525, ...,  0.59972667,
         0.04764356, -0.4563407 ],
       [ 0.02357709, -0.26964714, -0.0468987 , ..., -0.63347243,
        -0.42655357, -0.42261738],
       [ 0.90786397,  1.40906981,  0.8960605 , ..., -0.10734803,
        -2.15136216, -0.8893046 ],
       ...,
       [ 1.5039181 ,  2.13825538,  1.66970829, ...,  1.17298939,
        -0.12266667,  0.86865938],
       [-0.19189788,  0.6685262 , -0.22147576, ...,  0.17092008,
        -0.03417214, -0.83545607],
       [ 0.84629969,  1.17282277,  0.88390896, ...,  1.10912458,
         0.70383889,  2.6853672 ]])

In [9]:
y_train

244    M
298    B
213    M
30     M
246    B
      ..
216    B
209    B
256    M
49     B
72     M
Name: diagnosis, Length: 455, dtype: object

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [11]:
y_train

array([1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,

## NumPy arrays to PyTorch tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor

tensor([[ 1.4619,  0.9411,  1.4874,  ...,  0.5997,  0.0476, -0.4563],
        [ 0.0236, -0.2696, -0.0469,  ..., -0.6335, -0.4266, -0.4226],
        [ 0.9079,  1.4091,  0.8961,  ..., -0.1073, -2.1514, -0.8893],
        ...,
        [ 1.5039,  2.1383,  1.6697,  ...,  1.1730, -0.1227,  0.8687],
        [-0.1919,  0.6685, -0.2215,  ...,  0.1709, -0.0342, -0.8355],
        [ 0.8463,  1.1728,  0.8839,  ...,  1.1091,  0.7038,  2.6854]],
       dtype=torch.float64)

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

## Defining the model

In [21]:
class MySimpleNeuralNetwork(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

## Important parameters

In [22]:
learning_rate = 0.1
epochs = 25

In [24]:
loss_function = nn.BCELoss()

In [25]:
type(loss_function)

torch.nn.modules.loss.BCELoss

## Training pipeline

In [33]:
# create model
model = MySimpleNeuralNetwork(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor.float())

  # loss calculation
  loss = loss_function(y_pred, y_train_tensor.view(-1,1).float())

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f"Epoch {epoch}: Loss = {loss.item()}")

Epoch 0: Loss = 0.8059022426605225
Epoch 1: Loss = 0.5885111093521118
Epoch 2: Loss = 0.47989916801452637
Epoch 3: Loss = 0.4160447418689728
Epoch 4: Loss = 0.373080849647522
Epoch 5: Loss = 0.3416912853717804
Epoch 6: Loss = 0.31747856736183167
Epoch 7: Loss = 0.29806992411613464
Epoch 8: Loss = 0.28206029534339905
Epoch 9: Loss = 0.26855912804603577
Epoch 10: Loss = 0.256971538066864
Epoch 11: Loss = 0.24688349664211273
Epoch 12: Loss = 0.23799696564674377
Epoch 13: Loss = 0.23009127378463745
Epoch 14: Loss = 0.22299908101558685
Epoch 15: Loss = 0.2165910005569458
Epoch 16: Loss = 0.2107650637626648
Epoch 17: Loss = 0.20543965697288513
Epoch 18: Loss = 0.2005487084388733
Epoch 19: Loss = 0.19603781402111053
Epoch 20: Loss = 0.1918618381023407
Epoch 21: Loss = 0.18798282742500305
Epoch 22: Loss = 0.18436871469020844
Epoch 23: Loss = 0.1809920221567154
Epoch 24: Loss = 0.17782917618751526


In [34]:
model.linear.weight

Parameter containing:
tensor([[ 0.2364,  0.0806,  0.1819,  0.1692,  0.1195,  0.0866,  0.2945,  0.2843,
          0.0946, -0.0751,  0.1116, -0.1188,  0.3129,  0.0975,  0.0318, -0.0221,
          0.0136,  0.0685, -0.1221, -0.0274,  0.3787,  0.2988,  0.2077,  0.2343,
          0.0789,  0.1806,  0.1572,  0.3221,  0.0820,  0.0630]],
       requires_grad=True)

In [35]:
model.linear.bias

Parameter containing:
tensor([-0.0788], requires_grad=True)

## Evaluation

In [36]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor.float())
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5467836260795593
