In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
X, y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=12)

In [3]:
X

array([[ 0.90383352,  1.07700489],
       [-0.97480842,  1.01504085],
       [-1.50393841, -2.2999282 ],
       [ 0.8119954 ,  0.2162915 ],
       [-1.3262057 , -1.16148118],
       [ 1.07710384,  0.85084203],
       [-1.40802303,  0.56539468],
       [-1.96792039,  0.19577995],
       [ 1.56582116, -1.03896726],
       [-1.63146571, -1.66211952]])

In [4]:
X.shape

(10, 2)

In [5]:
y

array([1, 1, 0, 0, 0, 1, 1, 1, 0, 0])

In [6]:
y.shape

(10,)

In [8]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)

In [9]:
X

tensor([[ 0.9038,  1.0770],
        [-0.9748,  1.0150],
        [-1.5039, -2.2999],
        [ 0.8120,  0.2163],
        [-1.3262, -1.1615],
        [ 1.0771,  0.8508],
        [-1.4080,  0.5654],
        [-1.9679,  0.1958],
        [ 1.5658, -1.0390],
        [-1.6315, -1.6621]])

In [10]:
y

tensor([1., 1., 0., 0., 0., 1., 1., 1., 0., 0.])

In [11]:
from torch.utils.data import Dataset, DataLoader

In [12]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):

    return self.features.shape[0]

  def __getitem__(self, index):

    return self.features[index], self.labels[index]

In [13]:
dataset = CustomDataset(X, y)

In [14]:
len(dataset)

10

In [16]:
dataset[2]

(tensor([-1.5039, -2.2999]), tensor(0.))

In [20]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=False)

In [21]:
for batch_features, batch_labels in dataloader:

  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[ 0.9038,  1.0770],
        [-0.9748,  1.0150]])
tensor([1., 1.])
--------------------------------------------------
tensor([[-1.5039, -2.2999],
        [ 0.8120,  0.2163]])
tensor([0., 0.])
--------------------------------------------------
tensor([[-1.3262, -1.1615],
        [ 1.0771,  0.8508]])
tensor([0., 1.])
--------------------------------------------------
tensor([[-1.4080,  0.5654],
        [-1.9679,  0.1958]])
tensor([1., 1.])
--------------------------------------------------
tensor([[ 1.5658, -1.0390],
        [-1.6315, -1.6621]])
tensor([0., 0.])
--------------------------------------------------
