In [ ]:
import torch
import torch.nn as nn

In [ ]:
class Model_1(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1) #(input, output)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [ ]:
features = torch.rand(10,5)

model_1 = Model_1(features.shape[1])

model_1.forward(features)

tensor([[0.4198],
        [0.4419],
        [0.3678],
        [0.3906],
        [0.4390],
        [0.3376],
        [0.4029],
        [0.3968],
        [0.4005],
        [0.3368]], grad_fn=<SigmoidBackward0>)

In [ ]:
model_1.linear.weight

Parameter containing:
tensor([[-0.1696,  0.0846, -0.3725, -0.0968, -0.3564]], requires_grad=True)

In [ ]:
model_1.linear.bias

Parameter containing:
tensor([0.0410], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary

summary(model_1, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model_1                                  [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
class Model_2(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features, 3) #(input, output)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [ ]:
features = torch.rand(10,5)

model_2 = Model_2(features.shape[1])

model_2.forward(features)

tensor([[0.6851],
        [0.6985],
        [0.6713],
        [0.6741],
        [0.6894],
        [0.7041],
        [0.6912],
        [0.6593],
        [0.7266],
        [0.7119]], grad_fn=<SigmoidBackward0>)

In [ ]:
model_2.linear1.weight

Parameter containing:
tensor([[ 0.3947,  0.0068,  0.3319, -0.1284,  0.1961],
        [-0.0209,  0.3599,  0.4224,  0.1788,  0.2007],
        [-0.4175, -0.4189,  0.3712,  0.0983, -0.0966]], requires_grad=True)

In [ ]:
model_2.linear1.bias

Parameter containing:
tensor([ 0.4332, -0.2774, -0.1930], requires_grad=True)

In [ ]:
model_2.linear2.weight

Parameter containing:
tensor([[0.3773, 0.0695, 0.3081]], requires_grad=True)

In [ ]:
model_2.linear2.bias

Parameter containing:
tensor([0.4723], requires_grad=True)

In [ ]:
summary(model_2, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model_2                                  [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
class Model_3(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3), #(input, output)
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [ ]:
features = torch.rand(10,5)

model_3 = Model_3(features.shape[1])

model_3.forward(features)

tensor([[0.5767],
        [0.5727],
        [0.5718],
        [0.5601],
        [0.5715],
        [0.5750],
        [0.5413],
        [0.5654],
        [0.5750],
        [0.5738]], grad_fn=<SigmoidBackward0>)