In [ ]:
import torch
print(torch.__version__)

2.9.0+cu126


In [ ]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not avilable. Using CPU.")

GPU is available!
Using GPU: Tesla T4


# **Creating a Tensor**

In [ ]:
# using empty
a = torch.empty(2,3)

In [ ]:
# check type
type(a)
print(a)

tensor([[2.1715e-18, 2.3081e-12, 2.6302e+20],
        [6.1943e-04, 3.6022e-12, 6.9989e+22]])


In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.8280, 0.1507, 0.9808],
        [0.9443, 0.4190, 0.5168]])

In [ ]:
# use of seed
torch.rand(2,3)

tensor([[0.5127, 0.7431, 0.2107],
        [0.5047, 0.8519, 0.2412]])

In [ ]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# using arange
print(torch.arange(0,10,2))

# using linspace
print(torch.linspace(0,10,10))

# using eye
print(torch.eye(5))

# using full
print(torch.full((3,3), 5))

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# **Tensor Shapes**

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[138804697779424, 138804697779424, 138800113511920],
        [138804666939888,        11665536,        10666464]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.5150, 0.7819, 0.6519],
        [0.9068, 0.4281, 0.5165]])

# **Tensor Data Types**

In [ ]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float32)

tensor([1., 2., 3.])

In [ ]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
x.to(torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

# **Mathematical Operations**

## 1. Scalar operations

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.2116, 0.6371],
        [0.7877, 0.1125]])

In [ ]:
x + 2

tensor([[2.2116, 2.6371],
        [2.7877, 2.1125]])

In [ ]:
x - 2

tensor([[-1.7884, -1.3629],
        [-1.2123, -1.8875]])

In [ ]:
x * 3

tensor([[0.6348, 1.9114],
        [2.3630, 0.3375]])

In [ ]:
x / 3

tensor([[0.0705, 0.2124],
        [0.2626, 0.0375]])

In [ ]:
(x * 100) // 3 # integer division

tensor([[ 7., 21.],
        [26.,  3.]])

In [ ]:
((x * 100) // 3) % 2

tensor([[1., 1.],
        [0., 1.]])

In [ ]:
x ** 2

tensor([[0.0448, 0.4059],
        [0.6204, 0.0127]])

## 2. Element-wise operations

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.1045, 0.3285, 0.3788],
        [0.5596, 0.1886, 0.7921]])
tensor([[0.7367, 0.9328, 0.3134],
        [0.8953, 0.6868, 0.2459]])


In [ ]:
a + b

tensor([[0.8412, 1.2613, 0.6922],
        [1.4549, 0.8755, 1.0380]])

In [ ]:
a - b

tensor([[-0.6323, -0.6042,  0.0654],
        [-0.3357, -0.4982,  0.5462]])

In [ ]:
a * b

tensor([[0.0770, 0.3065, 0.1187],
        [0.5010, 0.1296, 0.1948]])

In [ ]:
a / b

tensor([[0.1418, 0.3522, 1.2087],
        [0.6250, 0.2747, 3.2215]])

In [ ]:
a ** b

tensor([[0.1893, 0.3541, 0.7377],
        [0.5946, 0.3180, 0.9443]])

In [ ]:
a % b

tensor([[0.1045, 0.3285, 0.0654],
        [0.5596, 0.1886, 0.0545]])

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## 3. Reduction operations

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10)
e

tensor([[9, 8, 3],
        [0, 0, 5]])

In [ ]:
torch.sum(e)

tensor(19)

In [ ]:
torch.sum(e, dim=0)

tensor([7, 6, 6])

In [ ]:
torch.sum(e, dim=1)

tensor([ 8, 11])

In [ ]:
torch.mean(e, dtype=torch.float32)

tensor(3.1667)

In [ ]:
torch.mean(e, dim=0, dtype=torch.float32)

tensor([3.5000, 3.0000, 3.0000])

In [ ]:
torch.mean(e, dim=1, dtype=torch.float32)

tensor([2.6667, 3.6667])

In [ ]:
torch.median(e)

tensor(3)

In [ ]:
torch.max(e)

tensor(9)

In [ ]:
torch.min(e)

tensor(0)

In [ ]:
torch.prod(e)

tensor(0)

In [ ]:
torch.std(e.to(torch.float32))

tensor(3.8687)

In [ ]:
torch.var(e.to(torch.float32))

tensor(14.9667)

In [ ]:
torch.argmax(e)

tensor(0)

In [ ]:
torch.argmin(e)

tensor(3)

## 4. Matrix operations

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[8, 3, 5],
        [9, 9, 1]])
tensor([[5, 5],
        [5, 0],
        [7, 7]])


In [ ]:
torch.matmul(f,g)

tensor([[90, 75],
        [97, 52]])

In [ ]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

In [ ]:
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
torch.transpose(f, 0, 1)

tensor([[8, 9],
        [3, 9],
        [5, 1]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[1., 7., 2.],
        [0., 7., 4.],
        [7., 6., 7.]])

In [ ]:
torch.det(h)

tensor(123.0000)

In [ ]:
torch.inverse(h)

tensor([[ 0.2033, -0.3008,  0.1138],
        [ 0.2276, -0.0569, -0.0325],
        [-0.3984,  0.3496,  0.0569]])

## 5. Comparison operations

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[8, 8, 3],
        [5, 6, 8]])
tensor([[6, 0, 1],
        [3, 1, 6]])


In [ ]:
i > j

tensor([[True, True, True],
        [True, True, True]])

In [ ]:
i < j

tensor([[False, False, False],
        [False, False, False]])

In [ ]:
i == j

tensor([[False, False, False],
        [False, False, False]])

In [ ]:
i >= j

tensor([[True, True, True],
        [True, True, True]])

In [ ]:
i <= j

tensor([[False, False, False],
        [False, False, False]])

## 6. Special functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 8., 0.],
        [9., 9., 7.]])

In [ ]:
torch.log(k)

tensor([[  -inf, 1.3863, 1.3863],
        [2.1972, 0.0000, 1.0986]])

In [ ]:
torch.exp(k)

tensor([[1.0000e+00, 5.4598e+01, 5.4598e+01],
        [8.1031e+03, 2.7183e+00, 2.0086e+01]])

In [ ]:
torch.sqrt(k)

tensor([[0.0000, 2.0000, 2.0000],
        [3.0000, 1.0000, 1.7321]])

In [ ]:
torch.sigmoid(k)

tensor([[0.5000, 0.9820, 0.9820],
        [0.9999, 0.7311, 0.9526]])

In [ ]:
torch.softmax(k, dim=0)

tensor([[2.4726e-03, 2.6894e-01, 9.1105e-04],
        [9.9753e-01, 7.3106e-01, 9.9909e-01]])

In [ ]:
torch.relu(k)

tensor([[3., 8., 0.],
        [9., 9., 7.]])

# **Inplace Operations**

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.1700, 0.4283, 0.0665],
        [0.4729, 0.7897, 0.4322]])
tensor([[0.1334, 0.8649, 0.2007],
        [0.2986, 0.4969, 0.7485]])


In [ ]:
m + n

tensor([[0.3034, 1.2931, 0.2672],
        [0.7716, 1.2866, 1.1807]])

In [ ]:
m.add_(n)

tensor([[0.3034, 1.2931, 0.2672],
        [0.7716, 1.2866, 1.1807]])

In [ ]:
m

tensor([[0.3034, 1.2931, 0.2672],
        [0.7716, 1.2866, 1.1807]])

In [ ]:
n

tensor([[0.1334, 0.8649, 0.2007],
        [0.2986, 0.4969, 0.7485]])

In [ ]:
torch.relu(m)

tensor([[0.3034, 1.2931, 0.2672],
        [0.7716, 1.2866, 1.1807]])

In [ ]:
m.relu_()

tensor([[0.3034, 1.2931, 0.2672],
        [0.7716, 1.2866, 1.1807]])

# **Copying a Tensor**

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.5054, 0.9062, 0.5489],
        [0.9989, 0.5125, 0.6636]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.5054, 0.9062, 0.5489],
        [0.9989, 0.5125, 0.6636]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.9062, 0.5489],
        [0.9989, 0.5125, 0.6636]])

In [ ]:
b

tensor([[0.0000, 0.9062, 0.5489],
        [0.9989, 0.5125, 0.6636]])

In [ ]:
id(a)

140090014743632

In [ ]:
id(b)

140090014743632

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.9062, 0.5489],
        [0.9989, 0.5125, 0.6636]])

In [ ]:
b

tensor([[0.0000, 0.9062, 0.5489],
        [0.9989, 0.5125, 0.6636]])

In [ ]:
id(a)

140090014743632

In [ ]:
id(b)

140088253337824

# **Tensor Operations on GPU**

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
torch.rand((2,3), device=device)

tensor([[0.8306, 0.4598, 0.0788],
        [0.3815, 0.8446, 0.4692]], device='cuda:0')

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.0050, 0.3371, 0.5098],
        [0.5803, 0.8760, 0.5151]])

In [ ]:
b = a.to(device)

In [ ]:
b

tensor([[0.0050, 0.3371, 0.5098],
        [0.5803, 0.8760, 0.5151]], device='cuda:0')

In [ ]:
import time

size = 10000

matrix_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"The time on CPU: {cpu_time:.4f} seconds")

matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
gpu_time = time.time() - start_time

print(f"The time on GPU: {gpu_time:.4f} seconds")

The time on CPU: 14.6693 seconds
The time on GPU: 0.1367 seconds


# **Reshaping Tensors**

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)
b

tensor([[[0.2129, 0.6918, 0.9742, 0.4058],
         [0.1417, 0.5854, 0.0302, 0.7918],
         [0.6166, 0.1452, 0.0392, 0.5076]],

        [[0.2576, 0.4022, 0.9272, 0.5812],
         [0.7667, 0.2740, 0.1050, 0.5506],
         [0.1165, 0.4332, 0.8491, 0.8392]]])

In [ ]:
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [ ]:
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# **NumPy and PyTorch**

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()

In [ ]:
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([1,2,3])

In [ ]:
d = torch.from_numpy(c)

In [ ]:
d

tensor([1, 2, 3])

In [ ]:
type(d)

torch.Tensor